### PR TITLE
parameter_list.h fixed

### PR DESCRIPTION
**Pull request by juandent**

### CODE REVIEW

**Comment by rbock** [comment]
Can you show me an example of a query that fails to compile without this fix? Please add a test case in tests/PreparedTest.cpp, for instance, to demonstrate the problem (and later the solution).

When you create the pull request for sqlpp11, please create it for the develop branch.

This comment of yours:
https://github.com/rbock/sqlpp11/issues/33#issuecomment-213900499
You replied to the sybase connector issue again. Is it related in any way? If not, please delete it, as it is confusing to have it there. It should be a comment to the issue you opened yourself.
When answering to issues per email: Please make sure that you answer to the correct one.

Also, in your issue here https://github.com/rbock/sqlpp11/issues/82, I assume you forgot to wrap your code in markdown? See the difference:

  template <typename... Parameter>
  struct parameter_list_t<detail::type_vector<Parameter...>> : public Parameter::_instance_t...

```C++
  template <typename... Parameter>
  struct parameter_list_t<detail::type_vector<Parameter...>> : public Parameter::_instance_t...
```

The second one is wrapped in triple-ticks plus language (```C++). It is then formatted as C++ code. It makes it much easier to read for others.

Thanks and best regards,

Roland

**Comment by juandent** [comment]
Hi Roland,

 

To see the problem, there is already a test that shows it. Please open the ‘sqlpp11-connector-mysql’ solution and build its ‘Sqlpp11MySQLDateTimeTest’ project. You will get 4 compiler errors one of which is related to the bug I have found (the other 3 I am not clear why they are occurring, but I have not done any changes at all so you should be able to reproduce them).

 

The relevant error is:

 


Severity

Code

Description

Project

File

Line

Suppression State


Error

C2440

'initializing': cannot convert from 'initializer list' to 'swallow'

Sqlpp11MySQLDateTimeTest

C:\Users\juan_\Documents\GitHub\sqlpp11\include\sqlpp11\parameter_list.h

65

 

 

This error is the one I describe in https://github.com/rbock/sqlpp11/issues/82, which I have formatted for easier reading as per your suggestion (thanks by the way!).

 

I have deleted the rbock#33 (comment) <https://github.com/rbock/sqlpp11/issues/33#issuecomment-213900499>  (sorry about the confusion). I hope this clears things up!

 

Regards,

Juan

**Comment by rbock** [comment]
With gcc I see no bug there (although there was one in another test, which is fixed now in develop).

I'm currently setting up travis CI. appveyor will be next.

**Comment by juandent** [comment]
I am using Visual Studio 2015 update 2

Are you saying you don't get the 4 compiler errors in the MySQL connector ?

Juan

**Comment by rbock** [comment]
Hi Juan,

With gcc, I don't.

That's why I will setup CI with appveyor, soon. I have no other suitable access to MSVC.

Best,

Roland

**Comment by juandent** [comment]
What is CI and appveyor?
Virtual machine?

Juan

**Comment by juandent** [comment]
Good!

I checked out the appveyor site.  Sounds useful to say the least  

What operating system do you use yo do your development?

Regards

Juan

**Comment by rbock** [comment]
I am using Ubuntu with clang/gcc.

Best,

Roland

**Comment by rbock** [comment]
Update: I finished integration with travis CI (develop branch). I fixed a few bugs while doing so. Maybe this also helps with MSVC?

I'll start integration with appveyor, soon.

Best,

Roland

**Pull request closed without merging**
